Sidebar UI, Scrolling Animation, and Other Changes (GitHub)
naveenrs123/pr-referencing-study-repo pull request #6
Opened 2022-04-11 15:58 UTC by naveenrs123

This PR contains the following changes:
- Reordered sidebar so that the image is now on top.
- Replaced "About" link with the image itself.
- Changed color of about section titles to green
- Change animation time when navigation links are clicked.

2022-04-11 18:07 UTC, randomion requested changes
Please see the comments I made on the code. Looks good in general, just a few minor things to fix/try.

2022-04-11 18:07 UTC, randomion commented on index.html
> +      <a href="#about"><img src="picrew-img.png" /></a>
If you do this, won't this not work with the bootstrap nav-link scrolling? Try this suggestion.
```suggestion
      <a href="#about" class="nav-link"><img src="picrew-img.png" /></a>
```

2022-04-11 18:07 UTC, randomion commented on index.html
> -        </div> -->
Shouldn't we keep the attribution?

2022-04-11 18:07 UTC, randomion commented on styles-media-queries.css
> +    font-size: 1.1rem;
```suggestion
    font-size: 1.0rem;
```
Since this is in a media query, maybe we should make it slightly smaller.

2022-04-11 18:07 UTC, randomion commented on styles.css
> +  color: #8ad47d;
This looks pale on my monitor, have you tried #51be3e?

2022-04-11 18:11 UTC, naveenrs123 commented on index.html
> +      <a href="#about"><img src="picrew-img.png" /></a>
Good catch, I think it will work with the on click function in `script.js`. I will give that a try.

2022-04-11 18:12 UTC, naveenrs123 commented on index.html
> -        </div> -->
I removed this because I don't think it goes in the sidebar. Maybe we should put it in the footer? @randomion

2022-04-11 18:13 UTC, naveenrs123 commented on styles-media-queries.css
> +    font-size: 1.1rem;
I think my original change makes more sense.

2022-04-11 18:18 UTC, naveenrs123 commented on index.html
> +      <a href="#about"><img src="picrew-img.png" /></a>
Tested it, the scrolling is back but there's now a border around the image because of the `.nav-link` styles. Let me find a better solution.

2022-04-12 19:58 UTC, naveenrs123 commented
SESSION[6255d9c50e00a753504bb417]_C[0]: [Hello what is going on with %[218]%]

2022-04-12 20:00 UTC, naveenrs123 commented
SESSION[6255d9c50e00a753504bb417]_C[0]: [Hello what is going on with %[218]%]

2022-04-14 19:39 UTC, closed without merging