Sidebar Changes, Font and Color Updates
naveenrs123/pr-referencing-study-repo pull request #7
Opened 2022-04-11 18:33 UTC by naveenrs123

This PR contains the following changes:
SESSION[62547387ccb90d3958f4e488]_C[0]: [Changed font-size of %[116]% to 8rem.]
SESSION[62547387ccb90d3958f4e488]_C[1]: [Sidebar (%[34]%) is now 240px wide.]
SESSION[62547387ccb90d3958f4e488]_C[2]: [Added Twitter contact link to sidebar. %[94]%]
SESSION[62547387ccb90d3958f4e488]_C[3]: [Changed the "Link to Project" text %[549]% CSS. Now the main change is a color change.]

2022-04-11 19:07 UTC, randomion requested changes
A few changes needed but looks good in general.

2022-04-11 19:07 UTC, randomion commented on index.html
> +            title="twitter"
```suggestion
            title="Twitter"
```

2022-04-11 19:07 UTC, randomion commented on index.html
> +        </div>
SESSION[62547b4fccb90d3958f4e489]_C[0]: [How about this layout instead?Add flex-wrap: wrap to the container and set the width of each element to 50%.]

2022-04-11 19:07 UTC, randomion commented on index.html
> -        </div> -->
Why are we not keeping this in the sidebar?

2022-04-11 19:12 UTC, naveenrs123 commented on styles.css
> +  font-size: 8rem;
Noted. I will test other sizes and see what looks best.

2022-04-11 19:12 UTC, naveenrs123 commented on index.html
> +            title="twitter"
Thanks, will update.

2022-04-11 19:16 UTC, naveenrs123 commented on index.html
> -        </div> -->
SESSION[62547387ccb90d3958f4e488]_C[1]: [Sidebar (%[34]%) is now 240px wide.]

The sidebar is already quite packed. With your suggestion in https://github.com/naveenrs123/pr-referencing-study-repo/pull/7#discussion_r847647448, the vertical space is further decreased. I don't want there to be scrolling issues on smaller screens.

2022-04-12 22:37 UTC, naveenrs123 commented
SESSION[6255feb70e00a753504bb418]_C[0]: [I am commenting on %[156]% as a test.]
SESSION[6255fee50e00a753504bb419]_C[1]: [This is a new session with a different reference. I am referencing %[473]% in this comment.]

2022-04-12 23:36 UTC, naveenrs123 commented
SESSION[6255dcebef36c087b4e5d1cd]_C[0]: [Updated text %[198]% in hobbies section %[196]%.]
SESSION[6255dcebef36c087b4e5d1cd]_C[1]: [Added icon attribution. %[94]%]
SESSION[6255dcebef36c087b4e5d1cd]_C[2]: [Change layout of the skills section %[226]% so that all 4 items fit on the same row.]
SESSION[6255dcebef36c087b4e5d1cd]_C[3]: [Change color of section titles from red to green e.g. %[223]% and %[268]%]
SESSION[6255dcebef36c087b4e5d1cd]_C[4]: [Change color of "Link to Project" %[504]% to green on hover.]

2022-04-13 04:54 UTC, naveenrs123 commented on index.html
> +        </div>
SESSION[6255fee50e00a753504bb419]_C[1]: [This is a new session with a different reference. I am referencing %[473]% in this comment.]

Test with this interface comment.

2022-04-13 04:54 UTC, naveenrs123 commented on index.html
> +        </div>
SESSION[6255fee50e00a753504bb419]_C[1]: [This is a new session with a different reference. I am referencing %[473]% in this comment.]

Test with this interface comment.

2022-04-13 04:57 UTC, naveenrs123 commented on index.html
> +        </div>
SESSION[6255fee50e00a753504bb419]_C[1]: [This is a new session with a different reference. I am referencing %[473]% in this comment.]

2022-04-13 04:58 UTC, naveenrs123 commented on styles.css
> +  font-size: 8rem;
SESSION[6255fee50e00a753504bb419]_C[1]: [This is a new session with a different reference. I am referencing %[473]% in this comment.]

2022-04-14 19:39 UTC, closed without merging